---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ua-web-nginx-conf
data:
  nginx.conf: |+
    user  root;
    worker_processes  10;
    
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    
    events {
      worker_connections  1024;
    }
    http {
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
      access_log  /var/log/nginx/access.log  main;

      underscores_in_headers on;
      proxy_buffer_size 10m;
      proxy_buffers 6 10m;
      proxy_busy_buffers_size 10m;
      proxy_temp_file_write_size 10m;

      client_header_timeout    2m; 
      client_body_timeout      2m; 
      
      proxy_connect_timeout 300;
      proxy_send_timeout 300;
      proxy_read_timeout 300; 
      
      fastcgi_buffers 8 256k;
      fastcgi_buffer_size 256k;
      fastcgi_busy_buffers_size 256k;
      fastcgi_temp_file_write_size 256k;
      
      fastcgi_connect_timeout 300;
      fastcgi_send_timeout 300;
      fastcgi_read_timeout 300;
      
      client_max_body_size 200M; 
      client_body_buffer_size 200M;
      
      sendfile            on;
      tcp_nopush          on;
      tcp_nodelay         on;
      keepalive_timeout   65;
      types_hash_max_size 2048;
      
      include             /etc/nginx/mime.types;
      default_type        application/octet-stream;
     
      server_tokens off;
      
      server {
        listen       80;
        listen  [::]:80 default_server;
        server_name  _;
        root    /usr/share/nginx/html;

        location /union-agent-web {
          add_header 'Access-Control-Allow-Origin' '*';
          add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
          add_header 'Access-Control-Allow-Credentials' 'true';
          add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,X-Data-Type,X-Requested-With,X-Data-Type,X-Auth-Token';
    
          if ( $request_method = 'OPTIONS' ) {
            return 200;
          }
    
          root /usr/share/nginx/html/;
          index index.html index.html;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ua-web
  labels:
    app: ua-web
    version: blue
spec:
  replicas: 1
  strategy: #部署策略-重建
    type: Recreate 
  selector:
    matchLabels:
      app: ua-web
      version: blue
  template:
    metadata:
      labels:
        app: ua-web
        version: blue
    spec:
      hostAliases: #配置内部域名解析
        - ip: "10.253.21.195"
          hostnames:
            - "ecloud.10086.cn"
      containers:
      - name: oos-web
        image: "cicdcsy.harbor.cmss.com:18080/ros/eoos/oos/ua-web:1.3.1_p1-12377864"
        volumeMounts:
          - mountPath: /var/log/nginx
            name: ua-web-logs
          - mountPath: /etc/nginx/nginx.conf
            name: ua-web-nginx-conf
            subPath: nginx.conf
        ports:
          - containerPort: 80
            protocol: TCP
      restartPolicy: Always
      volumes:
      - name: ua-web-logs
        hostPath:
          path: /apps/logs/bc-oos/guard/ua-web
      - name: ua-web-nginx-conf
        configMap:
          name: ua-web-nginx-conf
      imagePullSecrets:
      - name: harbor-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ua-web
spec:
  ipFamilyPolicy: PreferDualStack # 双栈策略
  ipFamilies:
    - IPv4
    - IPv6
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30262 
      name: http-port
  type: NodePort
  selector:
    app: ua-web

