# MySQL 数据库相关配置
mysql:
  addr: 10.253.217.137:3306 # MySQL 机器 ip 和端口，默认
  username: dnsuser # MySQL 用户名(建议授权最小权限集)
  password: 73s17bzJC+zGUOR4e9MvFw== # MySQL 用户密码
  database: eclouddns_slavezlf # 系统所用的数据库名
  max-idle-connections: 5 # MySQL 最大空闲连接数，默认 100
  max-open-connections: 5 # MySQL 最大打开的连接数，默认 100
  max-connection-life-time: 10s # 空闲连接最大存活时间，默认 10s

filepath:
  outPath: ./outputcsvs/ # 解析记录输出路径